spring:
  profiles:
    active: dev
  servlet:
    multipart:
      file-size-threshold: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  port: 8088
  servlet:
    context-path: /api/v1/        